### ISSUE TITLE
Aggiunta testimonianza Fondamenti Informatica-2011 2012-PsykeDady

### ISSUE THREAD

**Issue by PsykeDady** [UnicalLoveTelegram/IndiceArgomentiOrale#1]
# Ingegneria informatica LT

#### 2011 2012

- PsykeDady
    - Mergesort
        - scriverlo
        - complessità
            - O(log2n)
    - BubbleSort
    - esercizio

**Comment by PsykeDady** [comment]
> # Ingegneria informatica LT
> ## Fondamenti di Informatica
> ### Scarcello Francesco
> #### 2011 2012
> * PsykeDady
>   
>   * Mergesort
>     
>     * scriverlo
>     * complessità
>       
>       * O(log2n)
>   * BubbleSort
>   * esercizio

Ok, verrà aggiunta prossimamente Grazie!

**Comment by PsykeDady** [comment]
@Gionnix occupatene tu

**Comment by PsykeDady** [comment]
@PsykeDady ho finito rigenera i pdf

**Comment by Gionnix** [comment]
> @Gionnix occupatene tu

sto generando
