### ISSUE TITLE
Indice delle domande degli esami orali Ingegneria Informatica LT

### ISSUE THREAD

**Issue by giovixo97** [UnicalLoveTelegram/IndiceArgomentiOrale#10]
`ingegneria informatica LT`
 
**OPZIONALE** : ultimo aggiornamento della sessione 2020/2021
[Indice delle domande degli esami orali Ingegneria Informatica LT.pdf](https://github.com/UnicalLoveTelegram/IndiceArgomentiOrale/files/6426193/Indice.delle.domande.degli.esami.orali.Ingegneria.Informatica.LT.pdf)

**Comment by PsykeDady** [comment]
qua c'è un anomalia nella generazione, provo a rigenerarlo lato mio

**Comment by PsykeDady** [comment]
fbb8b60
