### ISSUE TITLE
Aggiunta testimonianza Ambienti di programmazione per il software di base -2022-ALFREDO

### ISSUE THREAD

**Issue by alfredofiore** [UnicalLoveTelegram/IndiceArgomentiOrale#13]
# ingegneria informatica LT

#### 2021/2022

- Alfredo
    - Permessi degli utenti e dei gruppi cosa sono?
    - Che differenza c'è tra un file .txt ed un file .bin
    - Demoni
    - Processi, cosa sono e come funzionano
    - Come si installano i pacchetti da repository
    - Le quote del disco cosa sono ed a cosa servono
    - cos'è il protocollo Samba?

**Comment by PsykeDady** [comment]
aggiornato con 042ee585b5bf0af9d629217947f476e2059d8541
