### ISSUE TITLE
Aggiunta testimonianza INGEGNERIA SOFTWARE 2022-2023

### ISSUE THREAD

**Issue by umbertocicciaa** [UnicalLoveTelegram/IndiceArgomentiOrale#16]
# INGEGNERIA INFORMATICA LT

#### Anno corso 2022-2023

- Anonimo
    - Decorator
        - Class Diagram
        - Sequence DIagram
        - Problema della super classe
        - Vantaggi rispetto ereditarietà
    - Proxy
        - Class Diagram
        - Remoto, Virtuale, Smart Pointer, Protezione
        - Esempi di utilizzi di proxy
        - Vantaggi proxy
    - Scrum
        - Scrum Backlog
    - Progetto
        - Design pattern utilizzati
        - Spiegazione delle scelte progettuali intraprese

**Comment by PsykeDady** [comment]
aggiornato con commit 32d901e9f995bf75cbdc9dd5e951bf529850b1c7 


Grazie <3
