### ISSUE TITLE
Aggiunta testimonianza RETI DI CALCOLATORI-2024

### ISSUE THREAD

**Issue by umbertocicciaa** [UnicalLoveTelegram/IndiceArgomentiOrale#18]
# corso di laurea - Ingegneria informatica LT

#### anno di riferimento ( quello di settembre ) - es: 2018/2019

- Marozzo 
    - Differenza tra container e macchina virtuale.
    - Blockchain: Algoritmo consenso, Struttura blocco, Proof of work.
    - Smart contract.
    - Processo per l'invio di mail sicure.
    - Differenza tra Soap e Rest dei web service.
 - Cosentino
    - Esercizio in cui bisognava mandare tramite i socket una richiesta HTTP Post
    - Nat

**Comment by giovixo97** [comment]
Forse intendi 2023 2024?

**Comment by umbertocicciaa** [comment]
si perdonami 🤣

**Comment by giovixo97** [comment]
Va benissimo, grazie mille

**Comment by PsykeDady** [comment]
Risolto con 5e397549173c7dddc4b9e6a7c7e64877ab8b7b17
