### ISSUE TITLE
Aggiunta testimonianza DATAMINING-2024

### ISSUE THREAD

**Issue by umbertocicciaa** [UnicalLoveTelegram/IndiceArgomentiOrale#19]
# nome corso di laurea -  Ingegneria informatica LT

#### anno di riferimento ( quello di settembre ) - 2023-2024

-  Anonimi 
    - Clustering col KMEANS
         - Come assegnare i punti al cluster più vicino
         - Come aggiornare i centroidi
         - Pseudocodice
         - Complessita
    - Campionamento
         - Perche si usa
         - Criterio con il quale si campiona

**Comment by PsykeDady** [comment]
risolto con 5e397549173c7dddc4b9e6a7c7e64877ab8b7b17
