### ISSUE TITLE
Intelligenza Artificiale-2020 2021-Francesco Arcuri

### ISSUE THREAD

**Issue by Francescolux** [UnicalLoveTelegram/IndiceArgomentiOrale#2]
# Ingegneria Informatica LM 

#### 2020/2021

- Anonimi 
  -  Davide dei un caca minchia?
        - se la cachi poi muori
        - intucu
    - domanda 2
    - domanda 3
etc...

**Comment by PsykeDady** [comment]
approvato ahhaha
