### ISSUE TITLE
 Intelligenza Artificiale 12CFU -2020/2021- Anonimo

### ISSUE THREAD

**Issue by Francescolux** [UnicalLoveTelegram/IndiceArgomentiOrale#6]
# Ingegneria Informatica LM

#### 2020/2021

- Verie testimonianze 04/02/2021
    - Descrizione algoritmo Iterative deepening
        - Precisare come si può uscire dal ciclo quando non ci sono goal 
        - **Risposta**: la soluzione proposta dal prof è quella di utilizzare una variabile booleana (non sappiamo nel dettaglio come), un'altra soluzione è quella di uscire quando il cutting level sia pari all'altezza dell'albero ma costa troppo in termini temporali
        
  - Complessità di verificare la coerenza di una teoria in logica di default (ossia se ammette un'estensione), dimostrare almeno intuitivamente perché tale problema è almeno NP-hard
    - **Risposta**: intuitivamente se la complessità dell'entailment è CONP-c in logica proposizionale, poiché la logica di default ha sia una teoria proposizionale W che un'insieme di default D è facile capire che sarà almeno difficile quanto l'entailment è quindi ha almeno una sorgente di esponenzialità
    
  - Strips genera stati inconsistenti? 
    - **Risposta**:un esempio è {f, not(f)} in cui abbiamo uno stato con due fluenti con valore logico opposto, ma strips NON è un linguaggio logico, f e not f potrebbero essere chiamati pluto e paperino quindi no, non genera stati inconsistenti in quanto il concetto di incosistenza è associato a linguaggi logici)
    
  - Esempio di teoria di default in cui non ci sia alcuna estensione che sia calcolabile con la semantica operazionale 
    - **Risposta**: basta usare una teoria incoerente, {TRUE:A/&not;A } è l'esempio tipico

**Comment by PsykeDady** [comment]
risolto con commit aec0f88ba4074449aa182ea4db5a391a02223eb4 
Grazie per la testimonianza, chiudo il thread
