### ISSUE TITLE
Indice delle domande degli esami orali Ingegneria Informatica LM

### ISSUE THREAD

**Issue by giovixo97** [UnicalLoveTelegram/IndiceArgomentiOrale#9]
`ingegneria informatica LM`
 
mancavano le testimonianze più recenti della sessione passata
[Indice delle domande degli esami orali Ingegneria Informatica LM.pdf](https://github.com/UnicalLoveTelegram/IndiceArgomentiOrale/files/6426175/Indice.delle.domande.degli.esami.orali.Ingegneria.Informatica.LM.pdf)

**Comment by PsykeDady** [comment]
già generato tu ?

**Comment by giovixo97** [comment]
si , ho fatto la issues per non fare danni

**Comment by PsykeDady** [comment]
fbb8b60
